server:
  port: 11000
spring:
  application:
    name: "provider-server"
  datasource:
    url: jdbc:mysql://localhost:3306/spring-exp?useSSL=false
    username: root
    password: 951753ASDasd
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"
