server:
  port: 12000
spring:
  application:
    name: "gateway-server"
  cloud:
    gateway:
      routes:
#当请求的路径以 /cartController/ 开头时，将请求转发到 http://cart-server
        - id: cartServer
          uri: lb://cart-server
          predicates:
            - Path=/CartController/**
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                fallbackUri: forward:/fallback

        - id: userServer
          uri: lb://user-server
          predicates:
            - Path=/UserController/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: backendA
#                fallbackUri: forward:/fallback

        - id: businessServer
          uri: lb://business-server
          predicates:
            - Path=/BusinessController/**
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                fallbackUri: forward:/fallback
        - id: foodServer
          uri: lb://food-server
          predicates:
            - Path=/FoodController/**
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                fallbackUri: forward:/fallback
        - id: ordersServer
          uri: lb://orders-server
          predicates:
            - Path=/OrdersController/**
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                fallbackUri: forward:/fallback
        - id: picOssServer
          uri: lb://picOss-server
          predicates:
            - Path=/oss/**
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                fallbackUri: forward:/fallback
                #        - id: daServer
                #          uri: lb://user-server
                #          predicates:
                #            - Path=/DeliveryAddressController/**


    global-cors:
      cors-configurations:
        '[/**]':
          allow-origins: "http://localhost:5173/"
          allow-methods: "GET,POST,HEAD,PUT,DELETE,OPTIONS"
          allow-headers: "*"


eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}" #本机标识
    #    每5s通信一次  15s内未响应从服务注册中心删除
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"

resilience4j:
  circuitbreaker:
    configs:
      default: #名字
        failure-rate-threshold: 30 #熔断器打开的失败阈值 %
        sliding-window-type: TIME_BASED #基于时间滑动窗的方式
        minimum-number-of-calls: 5
        sliding-window-size: 10000 # 设置时间窗口长度
        automatic-transition-from-open-to-half-open-enabled: true #自动打开到半关
        wait-duration-in-open-state: 5s #熔断器从打开到半开的时间
        permitted-number-of-calls-in-half-open-state: 3 #半开状态时运行通过的请求数
        record-exceptions: java.lang.Exception #记录异常
        register-health-indicator: false #健康检测
    instances:
      backendA:
        base-config: default

