server:
  port: 12000
spring:
  application:
    name: "gateway-server"
  cloud:
    gateway:
      routes:
        - id: consumerServer
          uri: lb://consumer-server
          predicates:
           - Path=/cart/**
            #                在网关中设置熔断器
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                fallbackUri: forward:/fallback
#当请求的路径以 /cart/ 开头时，将请求转发到 http://consumer-server:16000
        - id: providerServer
          uri: lb://provider-server
          predicates:
            - Path=/user/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                name: limiterA
#                fallbackUri: forward:/fallback2

    global-cors:
      cors-configurations:
        '[/**]':
          allow-origins: "*"
          allow-methods: "GET,POST,HEAD,PUT,DELETE"
          allow-headers: "*"



eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}" #本机标识
    #    每5s通信一次  15s内未响应从服务注册中心删除
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"

resilience4j:
  circuitbreaker:
    configs:
      default: #名字
        failure-rate-threshold: 30 #熔断器打开的失败阈值 %
        sliding-window-type: TIME_BASED #基于时间滑动窗的方式
        minimum-number-of-calls: 5
        sliding-window-size: 10000 # 设置时间窗口长度
        automatic-transition-from-open-to-half-open-enabled: true #自动打开到半关
        wait-duration-in-open-state: 5s #熔断器从打开到半开的时间
        permitted-number-of-calls-in-half-open-state: 3 #半开状态时运行通过的请求数
        record-exceptions: java.lang.Exception #记录异常
        register-health-indicator: false #健康检测
    instances:
      backendA:
        base-config: default

#  ratelimiter:
#    configs:
#      default:
#        limit-for-period: 100
#        limit-refresh-period:
#          seconds: 5
#          #20s之内放5个令牌
#        timeout-duration:
#          seconds: 5
#        #等待令牌时间
#    instances:
#      limiterA:
#        base-config: default
#

